name: Format and Linting with Eslint and Prettier
on: [push, pull_request]

jobs:
  Install-PNPM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: "pnpm"

  Eslint-And-Prettier:
    runs-on: ubuntu-latest
    steps:
      - run: pnpm run lint
      - run: pnpm run lint:fix
      - run: pnpm run format
